spring.application.name=spring-ai-chatbot
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4.1-mini
spring.ai.openai.chat.options.temperature=0.7
