server.port=9090
spring.application.name=spring-ai-chatbot
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4-turbo
spring.ai.openai.chat.options.temperature=0.7
